export type RegionOption = {
  label: string;
  value: string;
  type: 'region' | 'department';
  region?: string;
};

export const FRANCE_LOCATIONS: RegionOption[] = [
  // Île-de-France
  { label: 'Île-de-France', value: 'Île-de-France', type: 'region' },
  { label: '75 – Paris', value: 'Paris (75)', type: 'department', region: 'Île-de-France' },
  { label: '77 – Seine-et-Marne', value: 'Seine-et-Marne (77)', type: 'department', region: 'Île-de-France' },
  { label: '78 – Yvelines', value: 'Yvelines (78)', type: 'department', region: 'Île-de-France' },
  { label: '91 – Essonne', value: 'Essonne (91)', type: 'department', region: 'Île-de-France' },
  { label: '92 – Hauts-de-Seine', value: 'Hauts-de-Seine (92)', type: 'department', region: 'Île-de-France' },
  { label: '93 – Seine-Saint-Denis', value: 'Seine-Saint-Denis (93)', type: 'department', region: 'Île-de-France' },
  { label: '94 – Val-de-Marne', value: 'Val-de-Marne (94)', type: 'department', region: 'Île-de-France' },
  { label: "95 – Val-d'Oise", value: "Val-d'Oise (95)", type: 'department', region: 'Île-de-France' },
  // Auvergne-Rhône-Alpes
  { label: 'Auvergne-Rhône-Alpes', value: 'Auvergne-Rhône-Alpes', type: 'region' },
  { label: '01 – Ain', value: 'Ain (01)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '03 – Allier', value: 'Allier (03)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '07 – Ardèche', value: 'Ardèche (07)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '15 – Cantal', value: 'Cantal (15)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '26 – Drôme', value: 'Drôme (26)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '38 – Isère', value: 'Isère (38)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '42 – Loire', value: 'Loire (42)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '43 – Haute-Loire', value: 'Haute-Loire (43)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '63 – Puy-de-Dôme', value: 'Puy-de-Dôme (63)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '69 – Rhône', value: 'Rhône (69)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '73 – Savoie', value: 'Savoie (73)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  { label: '74 – Haute-Savoie', value: 'Haute-Savoie (74)', type: 'department', region: 'Auvergne-Rhône-Alpes' },
  // Bourgogne-Franche-Comté
  { label: 'Bourgogne-Franche-Comté', value: 'Bourgogne-Franche-Comté', type: 'region' },
  { label: '21 – Côte-d\'Or', value: "Côte-d'Or (21)", type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '25 – Doubs', value: 'Doubs (25)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '39 – Jura', value: 'Jura (39)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '58 – Nièvre', value: 'Nièvre (58)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '70 – Haute-Saône', value: 'Haute-Saône (70)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '71 – Saône-et-Loire', value: 'Saône-et-Loire (71)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '89 – Yonne', value: 'Yonne (89)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  { label: '90 – Territoire de Belfort', value: 'Territoire de Belfort (90)', type: 'department', region: 'Bourgogne-Franche-Comté' },
  // Bretagne
  { label: 'Bretagne', value: 'Bretagne', type: 'region' },
  { label: '22 – Côtes-d\'Armor', value: "Côtes-d'Armor (22)", type: 'department', region: 'Bretagne' },
  { label: '29 – Finistère', value: 'Finistère (29)', type: 'department', region: 'Bretagne' },
  { label: '35 – Ille-et-Vilaine', value: 'Ille-et-Vilaine (35)', type: 'department', region: 'Bretagne' },
  { label: '56 – Morbihan', value: 'Morbihan (56)', type: 'department', region: 'Bretagne' },
  // Centre-Val de Loire
  { label: 'Centre-Val de Loire', value: 'Centre-Val de Loire', type: 'region' },
  { label: '18 – Cher', value: 'Cher (18)', type: 'department', region: 'Centre-Val de Loire' },
  { label: '28 – Eure-et-Loir', value: 'Eure-et-Loir (28)', type: 'department', region: 'Centre-Val de Loire' },
  { label: '36 – Indre', value: 'Indre (36)', type: 'department', region: 'Centre-Val de Loire' },
  { label: '37 – Indre-et-Loire', value: 'Indre-et-Loire (37)', type: 'department', region: 'Centre-Val de Loire' },
  { label: '41 – Loir-et-Cher', value: 'Loir-et-Cher (41)', type: 'department', region: 'Centre-Val de Loire' },
  { label: '45 – Loiret', value: 'Loiret (45)', type: 'department', region: 'Centre-Val de Loire' },
  // Corse
  { label: 'Corse', value: 'Corse', type: 'region' },
  { label: '2A – Corse-du-Sud', value: 'Corse-du-Sud (2A)', type: 'department', region: 'Corse' },
  { label: '2B – Haute-Corse', value: 'Haute-Corse (2B)', type: 'department', region: 'Corse' },
  // Grand Est
  { label: 'Grand Est', value: 'Grand Est', type: 'region' },
  { label: '08 – Ardennes', value: 'Ardennes (08)', type: 'department', region: 'Grand Est' },
  { label: '10 – Aube', value: 'Aube (10)', type: 'department', region: 'Grand Est' },
  { label: '51 – Marne', value: 'Marne (51)', type: 'department', region: 'Grand Est' },
  { label: '52 – Haute-Marne', value: 'Haute-Marne (52)', type: 'department', region: 'Grand Est' },
  { label: '54 – Meurthe-et-Moselle', value: 'Meurthe-et-Moselle (54)', type: 'department', region: 'Grand Est' },
  { label: '55 – Meuse', value: 'Meuse (55)', type: 'department', region: 'Grand Est' },
  { label: '57 – Moselle', value: 'Moselle (57)', type: 'department', region: 'Grand Est' },
  { label: '67 – Bas-Rhin', value: 'Bas-Rhin (67)', type: 'department', region: 'Grand Est' },
  { label: '68 – Haut-Rhin', value: 'Haut-Rhin (68)', type: 'department', region: 'Grand Est' },
  { label: '88 – Vosges', value: 'Vosges (88)', type: 'department', region: 'Grand Est' },
  // Hauts-de-France
  { label: 'Hauts-de-France', value: 'Hauts-de-France', type: 'region' },
  { label: '02 – Aisne', value: 'Aisne (02)', type: 'department', region: 'Hauts-de-France' },
  { label: '59 – Nord', value: 'Nord (59)', type: 'department', region: 'Hauts-de-France' },
  { label: '60 – Oise', value: 'Oise (60)', type: 'department', region: 'Hauts-de-France' },
  { label: '62 – Pas-de-Calais', value: 'Pas-de-Calais (62)', type: 'department', region: 'Hauts-de-France' },
  { label: '80 – Somme', value: 'Somme (80)', type: 'department', region: 'Hauts-de-France' },
  // Normandie
  { label: 'Normandie', value: 'Normandie', type: 'region' },
  { label: '14 – Calvados', value: 'Calvados (14)', type: 'department', region: 'Normandie' },
  { label: '27 – Eure', value: 'Eure (27)', type: 'department', region: 'Normandie' },
  { label: '50 – Manche', value: 'Manche (50)', type: 'department', region: 'Normandie' },
  { label: '61 – Orne', value: 'Orne (61)', type: 'department', region: 'Normandie' },
  { label: '76 – Seine-Maritime', value: 'Seine-Maritime (76)', type: 'department', region: 'Normandie' },
  // Nouvelle-Aquitaine
  { label: 'Nouvelle-Aquitaine', value: 'Nouvelle-Aquitaine', type: 'region' },
  { label: '16 – Charente', value: 'Charente (16)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '17 – Charente-Maritime', value: 'Charente-Maritime (17)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '19 – Corrèze', value: 'Corrèze (19)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '23 – Creuse', value: 'Creuse (23)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '24 – Dordogne', value: 'Dordogne (24)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '33 – Gironde', value: 'Gironde (33)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '40 – Landes', value: 'Landes (40)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '47 – Lot-et-Garonne', value: 'Lot-et-Garonne (47)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '64 – Pyrénées-Atlantiques', value: 'Pyrénées-Atlantiques (64)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '79 – Deux-Sèvres', value: 'Deux-Sèvres (79)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '86 – Vienne', value: 'Vienne (86)', type: 'department', region: 'Nouvelle-Aquitaine' },
  { label: '87 – Haute-Vienne', value: 'Haute-Vienne (87)', type: 'department', region: 'Nouvelle-Aquitaine' },
  // Occitanie
  { label: 'Occitanie', value: 'Occitanie', type: 'region' },
  { label: '09 – Ariège', value: 'Ariège (09)', type: 'department', region: 'Occitanie' },
  { label: '11 – Aude', value: 'Aude (11)', type: 'department', region: 'Occitanie' },
  { label: '12 – Aveyron', value: 'Aveyron (12)', type: 'department', region: 'Occitanie' },
  { label: '30 – Gard', value: 'Gard (30)', type: 'department', region: 'Occitanie' },
  { label: '31 – Haute-Garonne', value: 'Haute-Garonne (31)', type: 'department', region: 'Occitanie' },
  { label: '32 – Gers', value: 'Gers (32)', type: 'department', region: 'Occitanie' },
  { label: '34 – Hérault', value: 'Hérault (34)', type: 'department', region: 'Occitanie' },
  { label: '46 – Lot', value: 'Lot (46)', type: 'department', region: 'Occitanie' },
  { label: '48 – Lozère', value: 'Lozère (48)', type: 'department', region: 'Occitanie' },
  { label: '65 – Hautes-Pyrénées', value: 'Hautes-Pyrénées (65)', type: 'department', region: 'Occitanie' },
  { label: '66 – Pyrénées-Orientales', value: 'Pyrénées-Orientales (66)', type: 'department', region: 'Occitanie' },
  { label: '81 – Tarn', value: 'Tarn (81)', type: 'department', region: 'Occitanie' },
  { label: '82 – Tarn-et-Garonne', value: 'Tarn-et-Garonne (82)', type: 'department', region: 'Occitanie' },
  // Pays de la Loire
  { label: 'Pays de la Loire', value: 'Pays de la Loire', type: 'region' },
  { label: '44 – Loire-Atlantique', value: 'Loire-Atlantique (44)', type: 'department', region: 'Pays de la Loire' },
  { label: '49 – Maine-et-Loire', value: 'Maine-et-Loire (49)', type: 'department', region: 'Pays de la Loire' },
  { label: '53 – Mayenne', value: 'Mayenne (53)', type: 'department', region: 'Pays de la Loire' },
  { label: '72 – Sarthe', value: 'Sarthe (72)', type: 'department', region: 'Pays de la Loire' },
  { label: '85 – Vendée', value: 'Vendée (85)', type: 'department', region: 'Pays de la Loire' },
  // Provence-Alpes-Côte d'Azur
  { label: "Provence-Alpes-Côte d'Azur", value: "Provence-Alpes-Côte d'Azur", type: 'region' },
  { label: '04 – Alpes-de-Haute-Provence', value: 'Alpes-de-Haute-Provence (04)', type: 'department', region: "Provence-Alpes-Côte d'Azur" },
  { label: '05 – Hautes-Alpes', value: 'Hautes-Alpes (05)', type: 'department', region: "Provence-Alpes-Côte d'Azur" },
  { label: '06 – Alpes-Maritimes', value: 'Alpes-Maritimes (06)', type: 'department', region: "Provence-Alpes-Côte d'Azur" },
  { label: '13 – Bouches-du-Rhône', value: 'Bouches-du-Rhône (13)', type: 'department', region: "Provence-Alpes-Côte d'Azur" },
  { label: '83 – Var', value: 'Var (83)', type: 'department', region: "Provence-Alpes-Côte d'Azur" },
  { label: '84 – Vaucluse', value: 'Vaucluse (84)', type: 'department', region: "Provence-Alpes-Côte d'Azur" },
  // Outre-mer
  { label: 'Outre-mer', value: 'Outre-mer', type: 'region' },
  { label: '971 – Guadeloupe', value: 'Guadeloupe (971)', type: 'department', region: 'Outre-mer' },
  { label: '972 – Martinique', value: 'Martinique (972)', type: 'department', region: 'Outre-mer' },
  { label: '973 – Guyane', value: 'Guyane (973)', type: 'department', region: 'Outre-mer' },
  { label: '974 – La Réunion', value: 'La Réunion (974)', type: 'department', region: 'Outre-mer' },
  { label: '976 – Mayotte', value: 'Mayotte (976)', type: 'department', region: 'Outre-mer' },
];

export const REGIONS = FRANCE_LOCATIONS.filter((l) => l.type === 'region').map((l) => l.value);
